---
title: "TDCJ Prison Heat"
---

This is for a group project under UT's Media Innovation Group. 

It is an examination of weather conditions recorded in prisons across the state of Texas using documents obtained through the Texas Department of Criminal Justice. More extensive sourcing information can be found on the project's cleaning files.

Looking at the navigation of this site, you'll mainly want to look at the files under the Analysis heading.

## Indoor logs 

We have recorded indoor temperatures for each unit April through September of 2022, 2023 and 2024 and April through July 25 (day the info request was filled) of 2025. According to the Texas Department of Criminal Justice, indoor temps are taken at 3 p.m. every day from April through September at all units that do not have air conditioning. The data was acquired by Lauren McGaughy at KUT through a public information request to the Texas Department of Criminal Justice.

For 2022, 2023 and 2024, we have 183 total days of indoor temperature recordings. As of Dec. 9, 2025, we only have 122 days of 2025 recordings, April 1 through July 25.

- Across all prisons in the data in from 2022-2024, it reached 85 degrees at least half the time.
- It reached 90 degrees at least a quarter of the time.
- It reached 100 degrees inside prisons more than 100 times in 2023.
- It reached 100 degrees indoors 210 times across all units between 2022 and 2025. Twice, it reached 105 or above. The hottest temperature recorded was the Mountain View unit on June 19, 2023, which reached 106.8 degrees. 
- In 2022, 53 of 68 units reached 85 degrees at least half of the days measured. In 2023, it was 54 of 68 units. 
- Twelve units reached 85 degrees on 75% of days measured in 2022.
- Ten units reached 85 degrees on 75% of days measured in 2023.
- In the Segovia unit in 2023, 94% of the days reached 85 degrees.
- Garza West reached 85 degrees on at least 80% of days each year since 2022. In 2022, 92% of days reached 85 degrees. 
- In 2023, 19 of 68 units reached 90 degrees at least half of the days measured.
- Two units reached 90 degrees for at least 75% of days measured, Segovia in 2023 and Garza West in 2024.
- Across all years, the Segovia and Garza West units consistently topped the charts for hottest temperatures recorded. 


## Outdoor logs

Lauren McGaughy of the Texas Newsroom public radio collaborative used a public information act to obtain the outdoor temperature logs kept by Texas prisons. The logs are hand-written and the data could not be accurately pulled through mechanical means, so a group of Media Innovation Group fellows transcribed a sample set of logs from each prison, from **July 24, 2023 through July 31, 2023**.

Here is what we found:

### Basics and legibility

**May 2025**

- We transcribed 8 days of logs for 82 units, making up about [15,700 rows of data](02-outdoor-readability.qmd#basic-information).
- If we found a row of the data was corrected or there was a question about the legibility, [we included a note](02-outdoor-readability.qmd#records-with-notes) within that row. We included some consistent-worded notes so we could count them, but also had some more free-form when those categories didn't fit. We tried to be consistent, but different humans were involved, so variability is inevitable. These based on the last seven days of July 2023.
    - About 15% of the records had notes.
    - About 1,300 records (7.5%) had corrections.
    - About 1,000 records (6.5%) we marked with legibility issues.
- Of those with notes, we also counted [what was at issue](02-outdoor-readability.qmd#variable-counts).    
    - There were about 650 notes concerning the heat index/wind chill column. That column is challenging because it captures two different things (though not at the same time). Some records also include what we determined was a heat risk category category, which we recorded in a separate column.
    - There were about 590 notes about the temperature column.
- We wanted to see [for which units we added notes](02-outdoor-readability.qmd#notes-by-unit).
    - More than 60% of the records for the Stevenson unit had notes, and many of those were flagged as "corrections". However, when you look at the [original document](https://drive.google.com/file/d/1s3pSZ7aU7lZHyKedz-P7DmVJIRmSUkSg/view?usp=drive_link), it appears the unit reviews the logs and clears up any legibility issues. i.e. having more corrections could be a positive thing.
    - In some cases we recorded an overall note about the unit as opposed to notes for each individual line. [They are printed in browsable form here](02-outdoor-readability.qmd#unit-notes).

### Precautionary measures

**August 2025 update**

Here we wanted to find which units should be under heat-related "precautionary measures" based on written data logs, and how that compared to actual Incident Command System activations.

This was challenging because the TDCJ definitions and directives to define if the unit should be in "precautionary measures" are ambiguous and confusing. See the [Precautionary measures](02-outdoor-protocols.qmd) notebook for a full discussion.

We ended up using the following definition: **When temperatures are 105+ degrees or heat index is 113+ for three or more consecutive days**.

We use the term "unit day" to describe when any of the 82 units meets a criteria on a single day.

Of our eight days of records from 82 prisons ...

- Seven units met the ICS criteria on some days for a total of 17 unit days, based on the definition given to us by the TDCJ communications department. None of those units had active ICS protocols in place on those days. This count could be low since units could have met protocol in the days before our time period.
- According to the activation data, there were 24 days in our time period where ICS heat mitigation protocols were put in place. On those activation days, none of these units met the criteria we've been given by TDCJ communications based on the weather logs kept by units. That said, half of the activations are within the first two days of our study, meaning they could have met the criteria in the days before our time frame.
- Out of 656 "unit days" possible (82 units, 8 days), excessive heat conditions (105 degrees or 113 heat index) were reached 127 times. Half of the units reached the criteria at least once. In only 12 of those instances was a unit in active precautionary measures.

There are also 15 "unit days" where there was no heat index values for that day, but the unit did include a heat index "risk category" that was Cat 3 or higher. Those are potentially 113 degrees or greater and would put the day in precautionary measures territory.

### Log accuracy vs weather stations

**May 2025**

> I'd like to take another crack at pairing these weather stations and include the distance the weather station is from the prison unit. [I've found a few issues](02-outdoor-reliability.qmd#ta-missing-weather-stations), along with some solutions to them, but they've yet to be implemented. For now, consider these stats with caution.

To gauge the accuracy of recorded temperature and humidity/heat index we paired each prison unit with a "nearby" weather station so we could compare the  temperatures.

- We don't have a good match for about 15% of the records.
- On average, temperatures are recorded [-2.9 degrees lower](02-outdoor-reliability.qmd#average-temp-difference) than the closest weather station.
- [About half](02-outdoor-reliability.qmd#percent-temp-within-range) of the temperatures are within 2 degrees, and 3/4ths are within 4 degrees.
    - You can [peruse these ranges by unit](02-outdoor-reliability.qmd#within-range-degrees-by-unit).
- The [heat index differences](02-outdoor-reliability.qmd#heat-index) are a little harder because of so much missing data, but we've charted them.

## Indoor temperatures

**July 2025 update**

While we did some earlier analysis of indoor temperatures in the spring, there were enough changes in the companion data that we need to check and rework it.

Here is what we'd like to find:

- What was the temperature inside on the days that units were under active ICS protocol?
- Are there days where inside a prison it was hotter than on the hottest day under protocol?
- How many days were above 85 degrees inside? 95? 100?

## Collaborators

Working on weather station data and analysis for indoor logs:

- Pearson Neal
- Johan Villatoro
- Ali Juell
- Karina Kumar

Ali Juell served as project lead and Christian McDonald mentored and edited.

Those transcribing the outdoor logs included:

- Emily deMotte
- Teresa Do
- Nicolas Pinto
- Diego Torrealba



